### ISSUE TITLE
FCGC.d64: 62, file not found,00,00 and crash, when launching the selected game

### ISSUE THREAD

**Issue by radius75** [WebFritzi/Assembly#1]
FCGC.d64
probably the missing hi-score file on the floppy causes the crash

--
Some procedure for checking the presence of the hi-score file would be useful, if it is not there, then the "default" hi-score setting

**Comment by WebFritzi** [comment]
Should work now. In fact, the games were missing on the disk. No idea, how this could happen. Thanks! You can also find a "cracked" version here: https://csdb.dk/release/?id=224695

**Comment by radius75** [comment]
Everything is fine now, fixed :)
