### ISSUE TITLE
You can get stuck in Minesweeper

### ISSUE THREAD

**Issue by radius75** [WebFritzi/Assembly#2]
Minesweeper from WinGames. Looks like you can get stuck and not finish the game. Placing a flag in a place where there is no mine will sometimes cause an "i" to appear. With which nothing can be done. Revealing all other squares does not end the game.
Is this a bug or am I doing something wrong?
![vice-screen-2023070122493505](https://github.com/WebFritzi/Assembler/assets/1929111/04037911-c6c9-436c-ab1e-b287ffe32516)
![vice-screen-2023070122500597](https://github.com/WebFritzi/Assembler/assets/1929111/2a44b358-91e2-4dd3-bcee-cea038009459)

**Comment by WebFritzi** [comment]
This seems to be a bug. Thank you, radius! I'll try to fix it.

**Comment by WebFritzi** [comment]
Hi radius75. Guess I fixed the issue. The "i" was there when the field has 1 adjacent mine. When there is no adjacent mine, there would have been an "M". These are the first two letters in "Minesweep" and appear as such in the character set. ;-) I resolved the issue by simply not opening flagged fields.

**Comment by radius75** [comment]
I've played it a few times and it's fine. Thank you.
