### ISSUE TITLE
WinGames.zip belongs to Releases

### ISSUE THREAD

**Issue by polluks2** [WebFritzi/Assembly#4]
Thanks for the nice games. Please extract the zip before committing.

**Comment by WebFritzi** [comment]
You're welcome. Why should I extract the zip?

**Comment by polluks2** [comment]
In a repository you want to browse the code, don't you?
How about a hint how to call ACME?

**Comment by WebFritzi** [comment]
Alright. I added the four asm files for the three games and the start menu. If you also want the binary files (e.g., for the maps), download the zip file.

**Comment by polluks2** [comment]
Thanks!
